version: '3.8'  # Specify the version of the Docker Compose file format


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: "kh+ufd1*0_oux(+#%5osqbq+&e=qrfe^w_s36v&k2u72-taf)!"
      DATABASE_URL: "postgresql+asyncpg://agora:postgres@postgres:5432/postgres"
      POSTGRES_USER: "agora"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      ALGORITHM: "HS256"
    depends_on:
      - postgres
    volumes:
      - ./alembic/versions:/app/alembic/versions

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "agora"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
