"""all delete orphans for conversation table

Revision ID: 0a5ce55f88db
Revises: 380d7748e48c
Create Date: 2024-10-24 07:49:52.974989

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a5ce55f88db"
down_revision: Union[str, None] = "380d7748e48c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
