"""delete cascade deleting the whole chat if someone deleted account

Revision ID: 395877b60f36
Revises: 769f8857eba9
Create Date: 2024-10-30 10:52:31.096708

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "395877b60f36"
down_revision: Union[str, None] = "769f8857eba9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
