"""back populates fixed

Revision ID: 44435ed9efb1
Revises: 82f6d1ae8df8
Create Date: 2024-10-09 08:53:15.717415

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "44435ed9efb1"
down_revision: Union[str, None] = "82f6d1ae8df8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
