"""added bio field for users table

Revision ID: 5bb9e6d43457
Revises: ccebc55438ff
Create Date: 2024-09-30 16:13:16.634684

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5bb9e6d43457"
down_revision: Union[str, None] = "ccebc55438ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("bio", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "bio")
    # ### end Alembic commands ###
