"""delete orhpan has been implemented for users conv and messages

Revision ID: 769f8857eba9
Revises: 87aa4646a676
Create Date: 2024-10-30 09:22:33.509353

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "769f8857eba9"
down_revision: Union[str, None] = "87aa4646a676"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
