"""changed pfp link default

Revision ID: 79c3cbf26af1
Revises: d988e6e4a99a
Create Date: 2024-11-04 20:41:20.383597

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "79c3cbf26af1"
down_revision: Union[str, None] = "d988e6e4a99a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
