"""added unique constraint that user can like only once

Revision ID: 852b57fa2932
Revises: 44435ed9efb1
Create Date: 2024-10-09 08:57:37.914326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852b57fa2932'
down_revision: Union[str, None] = '44435ed9efb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_post_like', 'post_likes', ['user_id', 'post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_post_like', 'post_likes', type_='unique')
    # ### end Alembic commands ###
