"""added new tablle for message files

Revision ID: 87aa4646a676
Revises: 0a5ce55f88db
Create Date: 2024-10-28 09:31:39.837967

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "87aa4646a676"
down_revision: Union[str, None] = "0a5ce55f88db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_files_messages_id"), "files_messages", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_files_messages_id"), table_name="files_messages")
    op.drop_table("files_messages")
    # ### end Alembic commands ###
