"""update field

Revision ID: 94dc8d6f0431
Revises: 9b6f3d789a15
Create Date: 2024-09-30 10:47:16.469689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94dc8d6f0431'
down_revision: Union[str, None] = '9b6f3d789a15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('_tags', sa.String(length=500), nullable=True))
    op.drop_column('posts', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tags', sa.VARCHAR(length=500), nullable=True))
    op.drop_column('posts', '_tags')
    # ### end Alembic commands ###
