"""added files field in posts table

Revision ID: b4109f0b26c8
Revises: 0fda28ad0687
Create Date: 2024-10-15 07:12:52.643890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4109f0b26c8'
down_revision: Union[str, None] = '0fda28ad0687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('files', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'files')
    # ### end Alembic commands ###
