"""added indexing for posts like table

Revision ID: d7a7c5cf1f03
Revises: 852b57fa2932
Create Date: 2024-10-09 18:19:38.404290

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d7a7c5cf1f03"
down_revision: Union[str, None] = "852b57fa2932"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_user_post", "post_likes", ["user_id", "post_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_post", table_name="post_likes")
    # ### end Alembic commands ###
