"""changed pfp link again

Revision ID: d988e6e4a99a
Revises: 3dbb4c098bd9
Create Date: 2024-11-04 16:46:15.413601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd988e6e4a99a'
down_revision: Union[str, None] = '3dbb4c098bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
