# Use the official PostgreSQL image as a parent image
FROM postgres:14-alpine

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=agora
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=postgres

# Expose the PostgreSQL port
EXPOSE 5432
